apiVersion: extension/v1beta1
kind: Ingress
metadata:
  name: "kakaonibs-ingress"
  namespace: default
  annotations:
    kubernetes.io/ingress.class: alb
    alb.ingress.kubernetes.io/scheme: internet-facing
spec:
  rules:
    - http:
        paths:     
           - backend:
              serviceName: react-frontend
              servicePort: 80
